Several misc fixes
nkinder/ansible-keycloak pull request #3
Opened 2019-01-21 10:32 UTC by jhrozek

A nicer error message, dependency trimming and avoid creating a local directory unless needed.

2019-01-21 13:02 UTC, nkinder commented on roles/keycloak/tasks/main.yml
> +  when: not keycloak_archive_on_target
This local directory is also used as the local destination when generating a pkcs12 file when PEM files are provided.  Perhaps we can just AND together multiple conditions here so we catch that case as well.

2019-01-21 13:05 UTC, nkinder requested changes
There is an additional condition (pkcs12 generation) where we use the local directory, which we need to check for.  Aside from that, this looks like a good change.

2019-01-22 07:54 UTC, nkinder commented on roles/keycloak/tasks/main.yml
> +    - java-openjdk-headless
I had to modify the OpenJDK dependency to specifically use 1.8.0 in my CI patch, so I just made this change as a part of that PR.  We can either drop this patch, or I can just rebase my work on top of this if we choose to merge your work first.

2019-01-29 12:00 UTC, jhrozek commented
I dropped the headless patch, but kept the other two as-as because PR #10 removes the other use of the `keycloak_local_download_dest` as it drops the block that generates the PKCS12 bundle. Perhaps it makes more sense to revisit this PR if/when PR#10 is merged, the changes here are more or less cosmetic after all.

2019-01-29 13:20 UTC, nkinder commented
I think we should get PR#10 merged first, then we can merge this.

2019-01-31 09:02 UTC, nkinder approved these changes

2019-01-31 09:02 UTC, merged